name: Build Yocto Image

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore: [ '**.md', '**.pdf', '**.yml' ]
  pull_request:
    branches: [ "master", "develop" ]
    paths-ignore: [ '**.md', '**.pdf', '**.yml' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build-yocto:
    runs-on: DC02
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Build the Docker image
      run: cd Build && ./build.sh; 
    
    - name: Run the Docker container and build output files
      run: |
        cd Build
        ./run.sh -c /home/github/rzv2l-cache
        cp output/images/smarc-rzv2l/*.wic.bz2 /home/github
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-image
        path: Build/output/images/smarc-rzv2l/mistysom-image-smarc-rzv2l.wic.bz2
