name: Build Yocto Image

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build-yocto:
    name: Build & Run the container
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: cd Build && ./build.sh -n; 
    
    - name: Run the Docker image and build output files with SDK
      run: cd Build && ./run.sh -c /home/github/rzv2l-cache -s;
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output-files
        path: |
          Output/Image-smarc-rzv2l.bin
          Output/r9a07g044l2-smarc.dtb
          Output/mistysom-image-smarc-rzv2l.tar.bz2
