name: FastForward Develop to match Master

on:
  push:
    branches: [ "master" ]

jobs:
  fast-forward-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Fast-Forward develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git merge origin/master
            git push --force origin HEAD:develop
