name: Release Submition

on: 
  push:
    branches: [master]

jobs:
  release-submittion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1.12
      with:
        draft: true
        generateReleaseNotes: true
        allowUpdates: true
        repo: master
        artifactErrorsFailBuild: true
        replacesArtifacts: true
        artifacts: "mistysom-image-smarc-rzv2l.wic.bz2"
