name: Release Submition

on: 
    workflow_run:
        workflows: ["Build Yocto Image"]
        branches: [master]
        types:
            - completed

jobs:
  fast-forward-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast-Forward develop
        env:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
        run: |
            git push --force origin/develop

  release-submittion:
    runs-on: DC02
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Generate Tag
      id: generate_tag
      run: |
        tag=$(git describe --tags --abbrev=0)
        IFS='.' read -ra parts <<< "$tag"
        last_part=${parts[-1]}
        last_part=$((last_part + 1))
        parts[-1]=$last_part
        new_tag=$(IFS='.'; echo "${parts[*]}")
        echo "tag=$new_tag" >> $GITHUB_OUTPUT

    - uses: ncipollo/release-action@v1.12.0
      with:
        draft: true
        generateReleaseNotes: true
        allowUpdates: true
        repo: master
        artifactErrorsFailBuild: true
        replacesArtifacts: true
        tag: ${{ steps.generate_tag.outputs.tag }}
        artifacts: "/home/github/mistysom-image-smarc-rzv2l.wic.bz2"
