name: Release Submition

on: 
  push:
    branches: [master]

jobs:
  fast-forward-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fast-Forward develop
        env:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
        run: |
            git push --force origin/develop

  release-submittion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1.12.0
      with:
        draft: true
        generateReleaseNotes: true
        allowUpdates: true
        repo: master
        artifactErrorsFailBuild: true
        replacesArtifacts: true
        artifacts: "mistysom-image-smarc-rzv2l.wic.bz2"
